const courses=[
 {id:1,title:'Desarrollo Web desde Cero',desc:'HTML, CSS, JavaScript y tu primer proyecto publicado.',level:'INICIAL',duration:'8 semanas',students:'1.8K',icon:'</>',cover:'cover-green'},
 {id:2,title:'JavaScript Profesional',desc:'Domina lógica, APIs, asincronía y aplicaciones modernas.',level:'INTERMEDIO',duration:'10 semanas',students:'1.2K',icon:'JS',cover:'cover-blue'},
 {id:3,title:'Datos e Inteligencia Artificial',desc:'Python, análisis de datos y fundamentos de IA aplicados.',level:'INTERMEDIO',duration:'12 semanas',students:'980',icon:'AI',cover:'cover-purple'},
 {id:4,title:'UX/UI Design',desc:'Investiga, diseña prototipos y crea experiencias digitales.',level:'INICIAL',duration:'7 semanas',students:'760',icon:'UX',cover:'cover-dark'},
 {id:5,title:'Ciberseguridad esencial',desc:'Fundamentos de seguridad, redes, amenazas y buenas prácticas.',level:'INTERMEDIO',duration:'9 semanas',students:'640',icon:'SEC',cover:'cover-green'},
 {id:6,title:'React + Proyectos reales',desc:'Componentes, estado, consumo de APIs y arquitectura frontend.',level:'AVANZADO',duration:'10 semanas',students:'530',icon:'R',cover:'cover-blue'}
];
const alumni=[['Laura M.','España','Frontend Developer'],['Andrés C.','México','Data Analyst'],['Sofía R.','Colombia','UX Designer'],['Daniel P.','Estados Unidos','Software Engineer'],['Camila V.','Chile','Product Designer']];
const DB={users:'tc_users',contacts:'tc_contacts',enrollments:'tc_enrollments'};
const read=k=>JSON.parse(localStorage.getItem(k)||'[]'); const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function seed(){if(!localStorage.getItem(DB.users)){write(DB.users,[{id:1,name:'Administrador',email:'admin@talentocaribe.com',password:'Admin123!',role:'admin',createdAt:new Date().toISOString()}])}if(!localStorage.getItem(DB.enrollments))write(DB.enrollments,[]);if(!localStorage.getItem(DB.contacts))write(DB.contacts,[])}seed();
const courseGrid=document.getElementById('courseGrid');
courseGrid.innerHTML=courses.map(c=>`<article class="course"><div class="course-cover ${c.cover}"><span class="course-icon">${c.icon}</span><span class="course-level">${c.level}</span></div><div class="course-body"><h3>${c.title}</h3><p>${c.desc}</p><div class="course-meta"><span>${c.duration}</span><span>${c.students} estudiantes</span></div><button class="btn btn-primary" style="width:100%;margin-top:15px" onclick="openEnroll(${c.id})">Ver curso <span>→</span></button></div></article>`).join('');
const backdrop=document.getElementById('modalBackdrop'), modalContent=document.getElementById('modalContent');
function openModal(type){backdrop.classList.add('show');if(type==='login')modalContent.innerHTML=`<h2>Bienvenido de nuevo.</h2><p>Ingresa a tu cuenta de Talento Caribe.</p><form class="auth-form" id="loginForm"><label>Correo<input name="email" type="email" required placeholder="tu@email.com"></label><label>Contraseña<input name="password" type="password" required placeholder="••••••••"></label><button class="btn btn-primary btn-lg">Ingresar</button><small class="auth-note">Demo administrador: admin@talentocaribe.com · Admin123!</small></form>`;if(type==='register')modalContent.innerHTML=`<h2>Crea tu cuenta.</h2><p>Tu próximo proyecto puede comenzar hoy.</p><form class="auth-form" id="registerForm"><label>Nombre completo<input name="name" required></label><label>Correo<input name="email" type="email" required></label><label>Contraseña<input name="password" type="password" minlength="6" required></label><button class="btn btn-primary btn-lg">Crear cuenta</button></form>`;if(type==='admin')showAdmin();}
function closeModal(){backdrop.classList.remove('show')}
document.querySelectorAll('[data-modal]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modal)));document.getElementById('modalClose').onclick=closeModal;backdrop.addEventListener('click',e=>{if(e.target===backdrop)closeModal()});
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
document.addEventListener('submit',e=>{if(e.target.id==='registerForm'){e.preventDefault();const f=new FormData(e.target),users=read(DB.users);if(users.some(u=>u.email===f.get('email'))){showToast('Ese correo ya está registrado.');return}users.push({id:Date.now(),name:f.get('name'),email:f.get('email'),password:f.get('password'),role:'student',createdAt:new Date().toISOString()});write(DB.users,users);closeModal();showToast('Cuenta creada. ¡Bienvenido a Talento Caribe!')}if(e.target.id==='loginForm'){e.preventDefault();const f=new FormData(e.target),u=read(DB.users).find(x=>x.email===f.get('email')&&x.password===f.get('password'));if(!u){showToast('Correo o contraseña incorrectos.');return}closeModal();if(u.role==='admin')openModal('admin');else showToast(`Hola ${u.name.split(' ')[0]}, tu sesión está activa.`)}});
function openEnroll(id){const c=courses.find(x=>x.id===id);modalContent.innerHTML=`<span class="kicker">MATRÍCULA</span><h2>${c.title}</h2><p>${c.desc}</p><form class="auth-form" id="enrollForm"><input type="hidden" name="courseId" value="${c.id}"><label>Nombre completo<input name="name" required placeholder="Tu nombre"></label><label>Correo electrónico<input name="email" type="email" required placeholder="tu@email.com"></label><label>Modalidad<select name="modality"><option>Virtual en vivo</option><option>A tu ritmo</option></select></label><button class="btn btn-primary btn-lg">Solicitar matrícula →</button></form>`;backdrop.classList.add('show');document.getElementById('enrollForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),arr=read(DB.enrollments);arr.push({id:Date.now(),courseId:Number(f.get('courseId')),name:f.get('name'),email:f.get('email'),modality:f.get('modality'),status:'pending',createdAt:new Date().toISOString()});write(DB.enrollments,arr);closeModal();showToast('Solicitud enviada. Te avisaremos por correo.')}}
document.getElementById('contactForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),arr=read(DB.contacts);arr.push({id:Date.now(),name:f.get('name'),email:f.get('email'),interest:f.get('interest'),message:f.get('message'),createdAt:new Date().toISOString()});write(DB.contacts,arr);e.target.reset();document.getElementById('contactStatus').textContent='✓ Solicitud guardada correctamente. Nuestro equipo te contactará.';showToast('¡Gracias! Recibimos tu mensaje.')};
document.getElementById('newsletter').onsubmit=e=>{e.preventDefault();showToast('¡Listo! Te suscribimos a Talento Caribe.');e.target.reset()};
function showAdmin(){const users=read(DB.users),en=read(DB.enrollments),co=read(DB.contacts);modalContent.innerHTML=`<div class="admin-panel"><span class="kicker">TALENTO CARIBE · ADMIN</span><h2>Centro de control</h2><div class="admin-stats"><div class="admin-stat"><strong>${users.length}</strong><span>usuarios registrados</span></div><div class="admin-stat"><strong>${en.length}</strong><span>solicitudes de matrícula</span></div><div class="admin-stat"><strong>${co.length}</strong><span>contactos recibidos</span></div></div><h3 style="font-size:18px;margin:18px 0 10px">Matrículas</h3>${en.length?`<table class="admin-table"><thead><tr><th>Estudiante</th><th>Curso</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${en.map(x=>`<tr><td>${x.name}<br><small>${x.email}</small></td><td>${courses.find(c=>c.id===x.courseId)?.title||'—'}</td><td><span class="status ${x.status}">${x.status==='pending'?'Pendiente':x.status==='accepted'?'Aceptada':'Rechazada'}</span></td><td class="row-actions"><button onclick="updateEnrollment(${x.id},'accepted')">Aceptar</button><button onclick="updateEnrollment(${x.id},'rejected')">Rechazar</button></td></tr>`).join('')}</tbody></table>`:'<p>No hay solicitudes todavía.</p>'}<h3 style="font-size:18px;margin:24px 0 10px">Usuarios</h3><table class="admin-table"><thead><tr><th>Nombre</th><th>Correo</th><th>Rol</th></tr></thead><tbody>${users.map(u=>`<tr><td>${u.name}</td><td>${u.email}</td><td>${u.role}</td></tr>`).join('')}</tbody></table></div>`;backdrop.classList.add('show')}
window.updateEnrollment=(id,status)=>{const a=read(DB.enrollments);const x=a.find(v=>v.id===id);if(x)x.status=status;write(DB.enrollments,a);showToast(status==='accepted'?'Matrícula aceptada.':'Matrícula rechazada.');showAdmin()};
document.getElementById('showAlumni').onclick=()=>{modalContent.innerHTML=`<span class="kicker">EGRESADOS</span><h2>Talento sin fronteras.</h2><p>Historias de personas que llevaron sus habilidades a nuevos equipos y mercados.</p><div class="admin-table">${alumni.map(a=>`<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;padding:13px 0;border-bottom:1px solid #e6ebef;font-size:12px"><strong>${a[0]}</strong><span>${a[1]}</span><span>${a[2]}</span></div>`).join('')}</div>`;backdrop.classList.add('show')};
document.getElementById('menuToggle').onclick=()=>document.getElementById('navLinks').classList.toggle('open');document.querySelectorAll('.nav-links a').forEach(a=>a.onclick=()=>document.getElementById('navLinks').classList.remove('open'));
